[2024-12-23 11:20:01,124] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T11:10:00+00:00 [queued]>
[2024-12-23 11:20:01,156] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T11:10:00+00:00 [queued]>
[2024-12-23 11:20:01,157] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-23 11:20:01,157] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2024-12-23 11:20:01,157] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-23 11:20:01,175] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): warsaw_data_update_dag_script> on 2024-12-23T11:10:00+00:00
[2024-12-23 11:20:01,182] {standard_task_runner.py:52} INFO - Started process 1063 to run task
[2024-12-23 11:20:01,191] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'warsaw_data_update_dag', 'warsaw_data_update_dag_script', '2024-12-23T11:10:00+00:00', '--job-id', '13', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/warsaw.py', '--cfg-path', '/tmp/tmphw59iydk', '--error-file', '/tmp/tmpf2m_vir5']
[2024-12-23 11:20:01,192] {standard_task_runner.py:77} INFO - Job 13: Subtask warsaw_data_update_dag_script
[2024-12-23 11:20:01,268] {logging_mixin.py:104} INFO - Running <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T11:10:00+00:00 [running]> on host 21ac49de6db4
[2024-12-23 11:20:01,385] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=warsaw_data_update_dag
AIRFLOW_CTX_TASK_ID=warsaw_data_update_dag_script
AIRFLOW_CTX_EXECUTION_DATE=2024-12-23T11:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-23T11:10:00+00:00
[2024-12-23 11:20:01,388] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-23 11:20:01,389] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts/ && python warsawUpdate.py']
[2024-12-23 11:20:01,411] {subprocess.py:75} INFO - Output:
[2024-12-23 11:20:02,497] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:20:02,497] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:20:02,497] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:20:02,497] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:20:02,498] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:20:02,498] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:20:02,498] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 11:20:02,498] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 11:20:02,498] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 11:13:36', 'hour': '11:13:36', 'temperature': 6.93}
[2024-12-23 11:20:02,527] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 11:10:16', 'hour': '11:10:16', 'temperature': 4.9}
[2024-12-23 11:20:02,527] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 11:10:07', 'hour': '11:10:07', 'temperature': 3.08}
[2024-12-23 11:20:02,527] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 11:12:40', 'hour': '11:12:40', 'temperature': 13.33}
[2024-12-23 11:20:02,529] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-23 11:20:02,610] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=warsaw_data_update_dag, task_id=warsaw_data_update_dag_script, execution_date=20241223T111000, start_date=20241223T112001, end_date=20241223T112002
[2024-12-23 11:20:02,679] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23 11:20:02,700] {local_task_job.py:151} INFO - Task exited with return code 0
